//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panaderia_DonDonas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donuts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donuts()
        {
            this.Donuts_Orders = new HashSet<Donuts_Orders>();
        }
    
        public int IdDonuts { get; set; }
        public string donutFlavor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donuts_Orders> Donuts_Orders { get; set; }
    }
}
