//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panaderia_DonDonas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donuts_Orders
    {
        public int IdDonuts_Orders { get; set; }
        public int IdOrder { get; set; }
        public int IdDonuts { get; set; }
        public int NumberOfDonuts { get; set; }
    
        public virtual Donuts Donuts { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
